version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql